#:schema node_modules/wrangler/config-schema.json
name = "resend-email-worker"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "*dou.gg/api/email", zone_name = "dou.gg" }
]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true